---
title: Calendar
---

***

<i class="fa fa-warning"></i> The following schedule is a *tentative* guideline and will be evolving to meet course needs up to and during the quarter.

In particular, the pace of the course will be adjusted so that we move as possible conditional on everyone "getting" the material.

***


### Key

<ul class="fa-ul">
<li><i class="fa fa-book"></i> Readings
<!-- <i class="fa fa-code"></i> Data Camp courses -->
<li><i class="fa fa-gears"></i> Actions to take </a>
<li><i class="fa fa-bar-chart"></i> Lessons </a>
<li><i class="fa fa-puzzle-piece"></i> Exams. </a>
<li><i class="fa fa-flask"></i> Labs. </a>
</ul>


* * *

#### Week 1-2: Introduction to Survey Design and Research Process

- **Topics:**
  - Overview of Survey Design
  - Introduction to Research Process



**Week 1**


<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>  Jan 22 Introduction to the course </a>
<li><i class="fa-li fa fa-book"></i>    Good intentions bad applications (survey deck on Canvas) </a>
<li><i class="fa-li fa fa-flask"></i>      Jan 22 Lab 0 - (Due Jan 26) <a target="_blank" href=./Labs/lab0/lab0.html>Introduction to the Course</a>

</ul>


**Week 2**

<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i>    - Chapters 1-2 of  Asher. </a>
<li><i class="fa-li fa fa-book"></i>   - Chapters 1-2 of  Dillman. </a>
<li><i class="fa-li fa fa-bar-chart"></i>  Jan 29 Data Collection + Observational studies & experiments <a target="_blank" href="./Slides/01_unit1/deck1/deck-1-1xxx.pdf"> </a>
<li><i class="fa-li fa fa-flask"></i>      Jan 29  Lab 1 (Due Feb 5)  <a href=./Labs/lab1/intro_to_r.html>Intro to R</a>
</ul>


#### Week 3-4: Introduction to Survey Design and Research Process

**Week 3**

<ul class="fa-ul">
<li><i class="fa-li fa fa-flask"></i>      Feb 5  Lab 2 (Due Feb 12)  <a href=./Labs/lab2/introduction_to_data.html> Introduction to Data</a>
</ul>


**Week 4**

<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i> Feb 12 Data Collection + Observational studies & experiments <a target="_blank" href="./Slides/01_unit1/deck1/deck-1-1.pdf"> Deck</a>
<li><i class="fa-li fa-gears"></i> Assignment: Surveys are everywhere! Good questions aren't </a>
</ul>



#### Week 5-6: Introduction to Statistical Inference

**Week 5**

<ul class="fa-ul">

<li><i class="fa-li fa fa-flask"></i>        Feb 26   Normal and binomial distribution <a target="_blank"  href="./Slides/02_unit2/deck3/u2_deck3.pdf"> Deck</a>
<li><i class="fa-li fa fa-flask"></i>      Feb 26  Lab Op1 (Due: )  <a href=./Labs/lab_ci/confidence_intervals.html> Confidence Intervals</a>

</ul>

**Week 5**


**Foundations for Inference** 

<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>    Mar 4 	Variability in estimates and CLT  <a target="_blank" href="./Slides/03_unit3/deck1/u3_deck1.pdf"> Deck </a>


</ul>


***

<!--
  


<li><i class="fa-li fa fa-bar-chart"></i>    Mar 4 	Confidence intervals  <a target="_blank" href="./Slides/03_unit3/deck2/u3_deck2.pdf"> Deck </a>
<li><i class="fa-li fa fa-bar-chart"></i>    Mar 9 	 Hypothesis tests  <a target="_blank" href="./Slides/03_unit3/deck3/u3_deck3.pdf"> Deck</a>


* * *

#### Week 3-4: Sampling Theory and Engaged Communities

- **Topics:**
  - Sampling Techniques
  - Engaged Communities

- **Readings:**
  - Chapter 4 “Sampling” (p.93-115) of *How to Conduct Surveys* (available on Canvas).
  - Assignment: Surveys are everywhere! Find a survey & upload it to Canvas.

#### Week 5-6: Probability-Based Methods

- **Topics:**
  - Probability-Based Sampling
  - Analysis of Family History of Incarceration Survey

- **Readings:**
  - Enns et al. 2019. [“What Percentage of Americans Have Ever Had a Family Member Incarcerated?"](https://doi.org/10.1177/2378023119829332)
  - Short Assignment: Watch [this video](https://youtu.be/sonXfzE1hvo) and answer questions.

#### Week 7-8: Non-Probability Methods

- **Topics:**
  - Evaluation of Online Nonprobability Surveys
  - Application in Political Science

- **Readings:**
  - Kennedy et al. 2016. [“Evaluating Online Nonprobability Surveys”](https://www.pewresearch.org/methods/2016/05/02/evaluating-online-nonprobability-surveys/)
  - Additional readings related to online surveys in political science.

#### Week 9-10: The Business of Survey Research

- **Topics:**
  - Market Research Surveys
  - Global Companies in Market Research

- **Readings:**
  - Survey Monkey. [Quick start guide on how to conduct market research](https://www.surveymonkey.com/mp/market-research-surveys/).
  - Additional readings on the business aspect of survey research.

#### Week 11-12: The Psychology of Survey Response

- **Topics:**
  - Influence of Question Wording
  - Psychological Processes in Survey Response

- **Readings:**
  - Schwarz, Norbert. 1999. [“Self-reports: How the questions shape the answers.”](Link to be added)
  - Short Assignment: Analyze a survey question using Schwarz's insights.

#### Week 13-14: Question Wording Effects & Survey Experiments

- **Topics:**
  - Experimental Design in Surveys
  - Analysis of Trump's Popularity

- **Readings:**
  - Druckman and Lupia. 2012. [“Experimenting with politics.”](Link to be added)
  - Enns and Schuldt. 2020. [“Trump May Be Even More Unpopular Than His Approval Rating Shows.”](https://fivethirtyeight.com/features/trump-may-be-even-more-unpopular-than-his-approval-rating-shows/)

#### Week 15: Data Literacy and How to Avoid Being Misled by Data

- **Topics:**
  - Understanding and Interpreting Data
  - Avoiding Misleading Interpretations

















***
***



<!--

### Unit 1

**Introduction**


<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>    Jan 22 Introduction to the course <a target = "_blank" href="./Slides/00_intro/topic0.pdf">Deck 0</a>
<li><i class="fa-li fa fa-flask"></i>        Jan 22 Lab 0 - (Due Jan 27) <a target="_blank" href=./Labs/lab0/lab0.html>Introduction to the Course</a>
<li><i class="fa-li fa fa-bar-chart"></i>    Jan 27 Data Collection + Observational studies & experiments <a target="_blank" href="./Slides/01_unit1/deck1/deck-1-1.pdf"> Deck</a>
<li><i class="fa-li fa fa-flask"></i>        Jan 29  Lab 1 (Due Feb 5) <a href=./Labs/lab1/intro_to_r.html>Intro to R</a>

<li><i class="fa-li fa fa-bar-chart"></i>    Feb 3 No Class Iowa Caucus


<li><i class="fa-li fa fa-bar-chart"></i>    Feb 5  More exploratory data analysis<a target="_blank" href="./Slides/01_unit1/u1_deck3/u1_deck3.pdf"> Deck</a>

<li><i class="fa-li fa fa-bar-chart"></i>    Feb 10 Introduction to statistical inference <a target="_blank" href="./Slides/01_unit1/u1_deck4/u1_deck4.pdf"> Deck </a>

<li><i class="fa-li fa fa-flask"></i>        Feb 12  Lab 2 (Due Feb 19) <a target="_blank" href=./Labs/lab2/introduction_to_data.html> Introduction to Data</a> 


</ul>
***
<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i> Reading:  OpenIntro -  Ch 2, Sec 2.1-2.3</a>
<li><i class="fa-li fa fa-gears"></i> Problem set (Due Feb 19)
  <ul>
  <li> Ch1:  1.2, 1.6, 1.16, 1.22, 1.30, 1.34, 2.15, 2.22, 2.24, 2.27.  </a>
  </ul>
</ul>
***
***

###  Unit 2

**Probability and Distribuitions**

<ul class="fa-ul">

<li><i class="fa-li fa fa-bar-chart"></i>    Feb 17 	Probability and conditional probability <a target="_blank" href="./Slides/02_unit2/deck1/u2_deck1.pdf"> Deck </a>
<li><i class="fa-li fa fa-bar-chart"></i>    Feb 19  Lab 3 - (Due Mar 4) <a target="_blank" href=./Labs/lab3/probability.html>Probability</a>	  
<li><i class="fa-li fa fa-bar-chart"></i>    Feb 24  	No class - February Break </a>

<li><i class="fa-li fa fa-flask"></i>        Feb 26   Normal and binomial distribution <a target="_blank"  href="./Slides/02_unit2/deck3/u2_deck3.pdf"> Deck</a>


</ul>


***

<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i> Reading:  OpenIntro - Ch 3 - Sec 3.1, 3.2 + Ch 4 - Sec 4.1, 4.4</a>
<li><i class="fa-li fa fa-gears"></i> Problem set (Due Mar 4)
  <ul> 
  <li> Ch 2: 2.2, 2.8, 2.18, 2.20, 2.22, 2.26
  <li> Ch 3: 3.4, 3.6, 3.12, 3.18, 3.26, 3.30, 3.36 </a>
  </ul>
</ul>
***
***



### Unit 3

**Foundations for Inference** 

<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>    Mar 2 	Variability in estimates and CLT  <a target="_blank" href="./Slides/03_unit3/deck1/u3_deck1.pdf"> Deck </a>
<li><i class="fa-li fa fa-bar-chart"></i>    Mar 4 	Confidence intervals  <a target="_blank" href="./Slides/03_unit3/deck2/u3_deck2.pdf"> Deck </a>
<li><i class="fa-li fa fa-bar-chart"></i>    Mar 9 	 Hypothesis tests  <a target="_blank" href="./Slides/03_unit3/deck3/u3_deck3.pdf"> Deck</a>
<li><i class="fa-li fa fa-flask"></i>        Mar 11  Lab 4 - (Due Apr 10 [Orig- Mar 18]) <a target="_blank" href=./Labs/lab4/confidence_intervals.html>Confidence intervals</a>
</ul>


***

<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i> Reading:  OpenIntro -  Ch 4</a>
<li><i class="fa-li fa fa-puzzle-piece"></i> **Midterm Canceled** </a>
</ul>


***
***

### Unit 4

**Inference**

<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>    Apr 6  Inference for numerical data  <a target="_blank" href="./Slides/04_unit4/deck1/u4_deck1.pdf"> Deck </a>
<li><i class="fa-li fa fa-flask"></i>        Apr 8  Lab 5 - (Due Apr 15 [Org - Mar 27]) <a target="_blank" href=./Labs/lab5/inf_for_numerical_data.html>Inference for numerical data</a>

<li><i class="fa-li fa fa-bar-chart"></i>    Apr 13  More inference  <a target="_blank" href="./Slides/04_unit4/deck4/u4_deck4.pdf"> Deck</a> 
<li><i class="fa-li fa fa-flask"></i>        Apr 15  Lab 6 - (Due Apr 29) <a target="_blank" href=./Labs/lab6/more_inf_for_numerical_data.html>(More) inference for numerical data</a>


<li><i class="fa-li  fa fa-exclamation"></i>    Mar 13- Apr 5 classes were canceled + Spring Break 

</ul>



***
<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i> Reading:  OpenIntro -  Ch. 5</a>
<li><i class="fa-li fa fa-microphone"></i> Apr 22 [Org March 25] Project presentation and paper
<li><i class="fa-li fa fa-gears"></i> Problem set (Due Apr 29 [Org 15]):    </a>
  <ul> 
  <li> Ch 4: 4.2, 4.8, 4.10, 4.12,  4.16, 4.20
  <li> Ch 5: 5.3, 5.4, 5.5, 5.6, 5.12, 5.20, 5.22 </a>
  </ul>
</ul>

***
***



### Unit 5
**Regression**


<ul class="fa-ul">
<li><i class="fa-li fa fa-bar-chart"></i>    Apr 20 Introduction linear regression  <a target="_blank" href="./Slides/06_unit6/deck1/u6_deck1.pdf"> Deck</a>
<li><i class="fa-li fa fa-flask"></i>        Apr 22  Lab 7 - (Due May 6) <a target="_blank" href=./Labs/lab7/simple_regression.html>Linear Regression</a>
<li><i class="fa-li fa fa-bar-chart"></i>    Apr 27 Multiple linear regression  <a target="_blank" href="./Slides/07_unit7/deck1/u7_deck1.pdf"> Deck</a>
<li><i class="fa-li fa fa-flask"></i>        Apr 29   Lab 8 - (Optional) <a target="_blank" href=./Labs/lab8//multiple_regression.html>Multiple Linear Regression Lab</a>

</ul>


***

<ul class="fa-ul">
<li><i class="fa-li fa fa-book"></i> Reading:  OpenIntro  - Ch 7 + Ch 8 - Sec 8.1, 8.2, 8.3</a>
</ul>

***
***


### Unit 6
**Presenting results**


<ul class="fa-ul">

<li><i class="fa-li fa fa-flask"></i>        May 4   Lecture/Lab <a target="_blank" href=./Labs/lab0/lab0.html>Predicted probabilities -  Visualizaton </a>
<li><i class="fa-li fa fa-flask"></i>        May 6    Lecture/Lab <a target="_blank" href=./Labs/lab0/lab0.html>Case study</a>
<li><i class="fa-li fa"></i>        May 11   Project Consulting
</ul>

***
***

### Final assessment

<ul class="fa-ul">
<li><i class="fa-li fa fa-microphone"></i>**Final Presentation Canceled** 
<li><i class="fa-li fa fa-file-text-o"></i> **May  22  Final Paper Due** 
</ul>

-->


